const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),register=require('../lib/business-stars');
const input={dishName:'Signature dish',dishPrice:100,diet:'vegetarian',menuUrl:'https://example.com/menu',popularityBasis:'signature',popularityEvidence:'Customers know our place for this dish.',consent:true};
function harness(rows,env={}){const routes={},writes=[];register({post:(p,fn)=>routes[p]=fn},async(strings,...values)=>{writes.push({query:strings.join('?'),values});return typeof rows==='function'?rows(strings.join('?'),values):rows;},{env});return {writes,async call(path,body={},headers={}){const res={code:200,set(){},status(n){this.code=n;return this},json(data){this.data=data;return this}};await routes[path]({body,headers},res);return res;}};}
test('owner claims can prove authority through GST, Google, Instagram, Zomato, or official sources',()=>{const gst=register.validateClaimProof({verificationMethod:'gst_registration',gstin:'27ABCDE1234F1Z5',ownershipEvidence:'The registered business name matches the selected directory listing.'});assert.equal(gst.profileUrl,'https://www.gst.gov.in/');assert.match(gst.ownershipEvidence,/GST registration/);assert.match(gst.ownershipEvidence,/27ABCDE1234F1Z5/);const options=[['google_business_profile','https://www.google.com/maps/place/example'],['instagram_business_profile','https://www.instagram.com/example/'],['zomato_business_profile','https://www.zomato.com/example'],['official_website','https://restaurant.example/about'],['other_official','https://example.gov.in/business/record']];for(const [verificationMethod,profileUrl] of options)assert.equal(register.validateClaimProof({verificationMethod,profileUrl,ownershipEvidence:'This official source shows the business contact details.'}).profileUrl,profileUrl);});
test('owner claim proof rejects malformed GSTINs, mismatched profiles, and unsafe links',()=>{const details='This official record links me with the selected business.';for(const gstin of ['','27ABCDE1234F1ZXX','bad'])assert.throws(()=>register.validateClaimProof({verificationMethod:'gst_registration',gstin,ownershipEvidence:details}));assert.throws(()=>register.validateClaimProof({verificationMethod:'instagram_business_profile',profileUrl:'https://instagram.com.evil.test/owner',ownershipEvidence:details}));assert.throws(()=>register.validateClaimProof({verificationMethod:'google_business_profile',profileUrl:'javascript:alert(1)',ownershipEvidence:details}));assert.throws(()=>register.validateClaimProof({verificationMethod:'other_official',profileUrl:'http://example.com',ownershipEvidence:details}));});
test('star submissions require price, menu, authority and popularity basis evidence',()=>{assert.equal(register.validateStar(input).isVeg,true);for(const patch of [{consent:false},{popularityEvidence:'yes'},{menuUrl:'javascript:alert(1)'},{slot:4},{popularityBasis:'viral'},{dishPrice:0}])assert.throws(()=>register.validateStar({...input,...patch}));});
test('private claim status rejects wrong access without exposing contact data',async()=>{const h=harness([{id:'11111111-1111-1111-1111-111111111111',tokenHash:'0'.repeat(64),email:'private@example.com'}]);const r=await h.call('/api/business-claims/status',{claimId:'11111111-1111-1111-1111-111111111111',accessCode:'a'.repeat(64)});assert.equal(r.code,403);assert.equal(JSON.stringify(r.data).includes('private@example'),false);});
test('pending owners cannot mutate live dishes; free owners cannot request paid slots',async()=>{const code='a'.repeat(64),c={id:'11111111-1111-1111-1111-111111111111',tokenHash:crypto.createHash('sha256').update(code).digest('hex'),restaurantId:1,status:'pending'};const h=harness(q=>q.includes('restaurant_star_limit')?[{capacity:1}]:[c]);let r=await h.call('/api/business-claims/star-dish',{...input,claimId:c.id,accessCode:code});assert.equal(r.code,409);c.status='approved';r=await h.call('/api/business-claims/star-dish',{...input,slot:2,claimId:c.id,accessCode:code});assert.equal(r.code,409);assert.equal(h.writes.some(w=>w.query.includes('INSERT')),false);});
test('review endpoints stay closed until private reviewer access is configured',async()=>{assert.equal((await harness([]).call('/api/business-claims/review-queue')).code,503);assert.equal((await harness([],{BUSINESS_REVIEW_KEY:'a'.repeat(32)}).call('/api/business-claims/review-queue',{},{})).code,403);});

test('pending claim corrections stay in review and never write live menus',async()=>{const code='b'.repeat(64),c={id:'11111111-1111-1111-1111-111111111111',tokenHash:crypto.createHash('sha256').update(code).digest('hex'),status:'needs_information'};const h=harness(q=>q.includes('SELECT *')?[c]:[{id:'revision'}]);const r=await h.call('/api/business-claims/correction',{...input,claimId:c.id,accessCode:code,city:'Mumbai',address:'Full address',profileUrl:'https://share.google/example',verificationMethod:'google_business_profile',ownershipEvidence:'Updated official contact for independent review.'});assert.equal(r.code,200);const mutation=h.writes.find(w=>w.query.includes('UPDATE'));assert.match(mutation.query,/status='pending'/);assert.match(mutation.query,/status IN \('pending','needs_information'\)/);assert.equal(h.writes.some(w=>/INSERT INTO public\."(Dish|Restaurant)"/.test(w.query)),false);});
test('approved ownership cannot be rewritten by pending-claim corrections',async()=>{const code='c'.repeat(64),c={id:'11111111-1111-1111-1111-111111111111',tokenHash:crypto.createHash('sha256').update(code).digest('hex'),status:'approved'};const h=harness(q=>q.includes('SELECT *')?[c]:[]);const r=await h.call('/api/business-claims/correction',{...input,claimId:c.id,accessCode:code,city:'Mumbai',address:'Full address',profileUrl:'https://www.google.com/maps',verificationMethod:'google_business_profile',ownershipEvidence:'Updated official contact for independent review.'});assert.equal(r.code,409);});
