const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),register=require('../lib/business-media');
const claimId='11111111-1111-4111-8111-111111111111',code='a'.repeat(64),hash=crypto.createHash('sha256').update(code).digest('hex');
function harness({status='approved',owns=true,mediaStatus='pending',fail=false}={}){const routes=new Map(),queries=[];register({post:(p,...h)=>routes.set(p,h.at(-1)),get:(p,h)=>routes.set(p,h)},async(strings,...values)=>{const q=strings.join('?');queries.push({q,values});if(fail)throw Error('offline');if(q.includes('FROM public."BusinessClaim"'))return [{id:claimId,restaurantId:10,tokenHash:hash,status}];if(q.includes('SELECT id FROM public."Dish"'))return owns?[{id:1}]:[];if(q.includes('SELECT mime,content,status'))return [{mime:'image/jpeg',content:'\\xffd8ff',status:mediaStatus}];if(q.includes('RETURNING id'))return [{id:claimId}];return [];},{env:{BUSINESS_REVIEW_KEY:'x'.repeat(32)}});return {queries,async request(path,{body,headers={},params={}}={}){let result,status=200,settings={};await routes.get(path)({body,headers,params},{set(k,v){settings[k]=v;},status(s){status=s;return this;},json(b){result=b;},send(b){result=b;},end(){}});return {status,body:result,settings};}};}
const upload={body:Buffer.from([255,216,255,0]),headers:{'x-claim-id':claimId,'x-media-kind':'dish','x-dish-id':'1','content-type':'image/jpeg','x-media-permission':'confirmed','x-ingredient-evidence':encodeURIComponent('Menu ingredients confirm the photographed vegetable sandwich.'),authorization:'Bearer '+code}};
test('owner photo upload stays pending and binds its exact dish identity',async()=>{const h=harness(),r=await h.request('/api/business-media/upload',upload);assert.equal(r.status,201);assert.match(r.body.message,/review/);const insert=h.queries.find(x=>x.q.includes('INSERT'));assert.equal(insert.values.includes(1),true);assert.equal(insert.q.includes("status='approved' SET"),false);});
test('pending owners and other-restaurant dishes cannot upload',async()=>{assert.equal((await harness({status:'pending'}).request('/api/business-media/upload',upload)).status,409);assert.equal((await harness({owns:false}).request('/api/business-media/upload',upload)).status,403);});
test('spoofed MIME, missing permission and incorrect owner code are rejected',async()=>{assert.equal((await harness().request('/api/business-media/upload',{...upload,body:Buffer.from('<script>bad</script>')})).status,400);assert.equal((await harness().request('/api/business-media/upload',{...upload,headers:{...upload.headers,'x-media-permission':''}})).status,400);assert.equal((await harness().request('/api/business-media/upload',{...upload,headers:{...upload.headers,authorization:'Bearer '+'b'.repeat(64)}})).status,403);});
test('unapproved media is private; approved bytes are public and nosniff',async()=>{const h=harness();assert.equal((await h.request('/api/business-media/:id',{params:{id:claimId}})).status,403);const r=await harness({mediaStatus:'approved'}).request('/api/business-media/:id',{params:{id:claimId}});assert.equal(r.status,200);assert.equal(r.body.toString('hex'),'ffd8ff');assert.equal(r.settings['X-Content-Type-Options'],'nosniff');});
test('media approval requires reviewer authentication and independent confirmation',async()=>{const h=harness();assert.equal((await h.request('/api/business-media/review',{body:{id:claimId,status:'approved'}})).status,403);assert.equal((await h.request('/api/business-media/review',{body:{id:claimId,status:'approved'},headers:{authorization:'Bearer '+'x'.repeat(32)}})).status,400);});
