const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),register=require('../lib/business-stars');
const input={dishName:'Signature dish',dishPrice:100,diet:'vegetarian',menuUrl:'https://example.com/menu',popularityBasis:'signature',popularityEvidence:'Customers know our place for this dish.',consent:true};
function harness(rows,env={}){const routes={},writes=[];register({post:(p,fn)=>routes[p]=fn},async(strings,...values)=>{writes.push({query:strings.join('?'),values});return typeof rows==='function'?rows(strings.join('?'),values):rows;},{env});return {writes,async call(path,body={},headers={}){const res={code:200,set(){},status(n){this.code=n;return this},json(data){this.data=data;return this}};await routes[path]({body,headers},res);return res;}};}
test('star submissions require price, menu, authority and popularity basis evidence',()=>{assert.equal(register.validateStar(input).isVeg,true);for(const patch of [{consent:false},{popularityEvidence:'yes'},{menuUrl:'javascript:alert(1)'},{slot:4},{popularityBasis:'viral'},{dishPrice:0}])assert.throws(()=>register.validateStar({...input,...patch}));});
test('private claim status rejects wrong access without exposing contact data',async()=>{const h=harness([{id:'11111111-1111-1111-1111-111111111111',tokenHash:'0'.repeat(64),email:'private@example.com'}]);const r=await h.call('/api/business-claims/status',{claimId:'11111111-1111-1111-1111-111111111111',accessCode:'a'.repeat(64)});assert.equal(r.code,403);assert.equal(JSON.stringify(r.data).includes('private@example'),false);});
test('pending owners cannot mutate live dishes; free owners cannot request paid slots',async()=>{const code='a'.repeat(64),c={id:'11111111-1111-1111-1111-111111111111',tokenHash:crypto.createHash('sha256').update(code).digest('hex'),restaurantId:1,status:'pending'};const h=harness(q=>q.includes('restaurant_star_limit')?[{capacity:1}]:[c]);let r=await h.call('/api/business-claims/star-dish',{...input,claimId:c.id,accessCode:code});assert.equal(r.code,409);c.status='approved';r=await h.call('/api/business-claims/star-dish',{...input,slot:2,claimId:c.id,accessCode:code});assert.equal(r.code,409);assert.equal(h.writes.some(w=>w.query.includes('INSERT')),false);});
test('review endpoints stay closed until private reviewer access is configured',async()=>{assert.equal((await harness([]).call('/api/business-claims/review-queue')).code,503);assert.equal((await harness([],{BUSINESS_REVIEW_KEY:'a'.repeat(32)}).call('/api/business-claims/review-queue',{},{})).code,403);});

test('pending claim corrections stay in review and never write live menus',async()=>{const code='b'.repeat(64),c={id:'11111111-1111-1111-1111-111111111111',tokenHash:crypto.createHash('sha256').update(code).digest('hex'),status:'needs_information'};const h=harness(q=>q.includes('SELECT *')?[c]:[{id:'revision'}]);const r=await h.call('/api/business-claims/correction',{...input,claimId:c.id,accessCode:code,city:'Mumbai',address:'Full address',profileUrl:'https://share.google/example',ownershipEvidence:'Updated official contact for independent review.'});assert.equal(r.code,200);const mutation=h.writes.find(w=>w.query.includes('UPDATE'));assert.match(mutation.query,/status='pending'/);assert.match(mutation.query,/status IN \('pending','needs_information'\)/);assert.equal(h.writes.some(w=>/INSERT INTO public\."(Dish|Restaurant)"/.test(w.query)),false);});
test('approved ownership cannot be rewritten by pending-claim corrections',async()=>{const code='c'.repeat(64),c={id:'11111111-1111-1111-1111-111111111111',tokenHash:crypto.createHash('sha256').update(code).digest('hex'),status:'approved'};const h=harness(q=>q.includes('SELECT *')?[c]:[]);const r=await h.call('/api/business-claims/correction',{...input,claimId:c.id,accessCode:code,city:'Mumbai',address:'Full address',profileUrl:'https://www.google.com/maps',ownershipEvidence:'Updated official contact for independent review.'});assert.equal(r.code,409);});

test('owner menu edits reject coerced prices and implicit slot zero without database writes',async()=>{for(const patch of [{dishPrice:true},{dishPrice:[100]},{dishPrice:{value:100}},{dishPrice:'1e2'},{dishPrice:1.001},{slot:0},{slot:null},{slot:true},{slot:[1]}]){assert.throws(()=>register.validateStar({...input,...patch}));const h=harness([]);const r=await h.call('/api/business-claims/star-dish',{...input,...patch});assert.equal(r.code,400);assert.equal(h.writes.length,0);}assert.equal(register.validateStar({...input,dishPrice:'100.50',slot:'2'}).price,100.5);});

test('website and social ownership claims remain pending and do not publish live dishes',async()=>{
 for(const profileUrl of ['https://www.instagram.com/examplecafe/','https://www.facebook.com/examplecafe','https://example.com/']){
  const h=harness(q=>q.includes('FROM public."Restaurant"')?[{name:'Example Cafe',city:'Mumbai',address:'Full branch address',restaurantId:1}]:[]);
  const r=await h.call('/api/business-claims',{...input,businessId:'restaurant:1',contactName:'Example Owner',email:'owner@example.com',phone:'9999999999',profileUrl,ownershipEvidence:'Verify authority using the published official business contact.'});
  assert.equal(r.code,201);assert.ok(r.data.claimId);assert.equal(r.data.status,undefined);
  const insert=h.writes.find(w=>w.query.includes('WITH claim AS'));assert.ok(insert.values.includes(profileUrl));assert.ok(insert.query.includes('"BusinessClaim"'));assert.ok(insert.query.includes('"StarDishRevision"'));
  assert.equal(h.writes.some(w=>/INSERT INTO public\."(Dish|Restaurant)"|approve_business_claim|approve_star_revision/.test(w.query)),false);
 }
});
test('social profile corrections still require owner credentials and independent approval',async()=>{
 const profileUrl='https://www.instagram.com/examplecafe/',body={...input,city:'Mumbai',address:'Full address',profileUrl,ownershipEvidence:'Updated official business contact for independent review.'};
 const denied=harness([]);assert.equal((await denied.call('/api/business-claims/correction',body)).code,403);assert.equal(denied.writes.length,0);
 const code='d'.repeat(64),c={id:'11111111-1111-1111-1111-111111111111',tokenHash:crypto.createHash('sha256').update(code).digest('hex'),status:'needs_information'};
 const h=harness(q=>q.includes('SELECT *')?[c]:[{id:'revision'}]);assert.equal((await h.call('/api/business-claims/correction',{...body,claimId:c.id,accessCode:code})).code,200);
 const write=h.writes.find(w=>w.query.includes('UPDATE'));assert.ok(write.values.includes(profileUrl));assert.match(write.query,/status='pending'/);assert.match(write.query,/status IN \('pending','needs_information'\)/);
});
test('invalid ownership profile is rejected before database work',async()=>{
 const h=harness([]);const r=await h.call('/api/business-claims/correction',{...input,city:'Mumbai',address:'Full address',profileUrl:'https://owner:secret@example.com/',ownershipEvidence:'Updated official contact for independent review.'});assert.equal(r.code,400);assert.equal(h.writes.length,0);
});

test('saved correction details require owner authentication and expose only an explicit whitelist',async()=>{
 const code='e'.repeat(64),c={id:'11111111-1111-1111-1111-111111111111',tokenHash:crypto.createHash('sha256').update(code).digest('hex'),status:'needs_information',businessName:'Example Cafe',city:'Mumbai',address:'Exact branch',profileUrl:'https://www.instagram.com/example/',ownershipEvidence:'Official contact evidence',email:'private@example.com',phone:'9999999999',reviewNotes:'Private reviewer notes'};
 const dish={name:'Poha',price:65,isVeg:true,menuUrl:'https://example.com/menu',popularityBasis:'signature',popularityEvidence:'Owner supplied evidence',reviewNotes:'Private dish notes'};
 const h=harness(q=>q.includes('SELECT *')?[c]:[dish]);const r=await h.call('/api/business-claims/edit-details',{claimId:c.id,accessCode:code});assert.equal(r.code,200);assert.equal(r.data.details.dish.diet,'vegetarian');assert.equal(r.data.details.dish.dishPrice,65);assert.equal(r.data.details.ownershipEvidence,c.ownershipEvidence);
 for(const secret of [c.tokenHash,c.email,c.phone,c.reviewNotes,dish.reviewNotes])assert.ok(!JSON.stringify(r.data).includes(secret));assert.ok(h.writes.every(w=>w.query.trim().startsWith('SELECT')));
 const denied=harness([c]);assert.equal((await denied.call('/api/business-claims/edit-details',{claimId:c.id,accessCode:'f'.repeat(64)})).code,403);assert.equal(denied.writes.length,1);
 const empty=harness([]);assert.equal((await empty.call('/api/business-claims/edit-details',{})).code,403);assert.equal(empty.writes.length,0);
});
test('approved and rejected owners cannot restore pending ownership corrections',async()=>{
 const code='e'.repeat(64);for(const status of ['approved','rejected']){const c={id:'11111111-1111-1111-1111-111111111111',tokenHash:crypto.createHash('sha256').update(code).digest('hex'),status};const h=harness([c]);const r=await h.call('/api/business-claims/edit-details',{claimId:c.id,accessCode:code});assert.equal(r.code,409);assert.equal(h.writes.length,1);assert.equal(r.data.details,undefined);}
});
test('saved details preserve unknown diet and unavailable dish without fabricating facts',async()=>{
 const code='e'.repeat(64),c={id:'11111111-1111-1111-1111-111111111111',tokenHash:crypto.createHash('sha256').update(code).digest('hex'),status:'pending'};for(const rows of [[],[{name:'Unknown diet dish',price:100,isVeg:null}]]){const h=harness(q=>q.includes('SELECT *')?[c]:rows);const r=await h.call('/api/business-claims/edit-details',{claimId:c.id,accessCode:code});assert.equal(r.code,200);assert.equal(rows.length?r.data.details.dish.diet:r.data.details.dish,null);}
});

test('approved owners load only the exact claim and permitted dish slot without private notes',async()=>{
 const code='e'.repeat(64),c={id:'11111111-1111-1111-1111-111111111111',tokenHash:crypto.createHash('sha256').update(code).digest('hex'),status:'approved',restaurantId:1},dish={slot:2,name:'Fish curry',price:250,isVeg:false,menuUrl:'https://example.com/menu',popularityBasis:'signature',popularityEvidence:'Owner evidence',status:'needs_information',reviewNotes:'Private review note',tokenHash:'PRIVATE'};
 const h=harness(q=>q.includes('SELECT *')?[c]:q.includes('restaurant_star_limit')?[{capacity:2}]:[dish]);const r=await h.call('/api/business-claims/dish-edit-details',{claimId:c.id,accessCode:code,slot:'2'});assert.equal(r.code,200);assert.equal(r.data.slot,2);assert.equal(r.data.dish.diet,'non-vegetarian');assert.equal(r.data.reviewStatus,'needs_information');assert.ok(!JSON.stringify(r.data).includes('Private review note'));assert.ok(!JSON.stringify(r.data).includes('PRIVATE'));const query=h.writes.at(-1);assert.match(query.query,/WHERE "claimId"=\?::uuid AND slot=\?/);assert.deepEqual(query.values,[c.id,2]);assert.ok(h.writes.every(w=>w.query.startsWith('SELECT')));
});
test('dish restore rejects invalid slots, wrong credentials, unapproved claims and expired plan slots',async()=>{
 for(const slot of [0,null,true,[1],4]){const h=harness([]);assert.equal((await h.call('/api/business-claims/dish-edit-details',{slot})).code,400);assert.equal(h.writes.length,0);}
 const empty=harness([]);assert.equal((await empty.call('/api/business-claims/dish-edit-details',{slot:1})).code,403);assert.equal(empty.writes.length,0);
 const code='e'.repeat(64),c={id:'11111111-1111-1111-1111-111111111111',tokenHash:crypto.createHash('sha256').update(code).digest('hex'),status:'pending',restaurantId:1},body={claimId:c.id,accessCode:code,slot:2};
 const h=harness(q=>q.includes('SELECT *')?[c]:[{capacity:1}]);assert.equal((await h.call('/api/business-claims/dish-edit-details',body)).code,409);assert.equal(h.writes.length,1);c.status='approved';const limited=harness(q=>q.includes('SELECT *')?[c]:[{capacity:1}]);assert.equal((await limited.call('/api/business-claims/dish-edit-details',body)).code,409);assert.equal(limited.writes.length,2);
 const wrong=harness([c]);assert.equal((await wrong.call('/api/business-claims/dish-edit-details',{...body,accessCode:'f'.repeat(64)})).code,403);assert.equal(wrong.writes.length,1);
});
test('dish restore leaves missing records absent and fails closed on unknown plan allowance',async()=>{
 const code='e'.repeat(64),c={id:'11111111-1111-1111-1111-111111111111',tokenHash:crypto.createHash('sha256').update(code).digest('hex'),status:'approved',restaurantId:1},body={claimId:c.id,accessCode:code,slot:1};
 const missing=harness(q=>q.includes('SELECT *')?[c]:q.includes('restaurant_star_limit')?[{capacity:1}]:[]);assert.equal((await missing.call('/api/business-claims/dish-edit-details',body)).code,404);
 const unavailable=harness(q=>q.includes('SELECT *')?[c]:[]);assert.equal((await unavailable.call('/api/business-claims/dish-edit-details',body)).code,503);assert.equal(unavailable.writes.length,2);
});
