const test=require('node:test'),assert=require('node:assert/strict');
const register=require('../lib/business-review');
async function run(path,body={},key='k'.repeat(32),configured=key){const routes=new Map(),queries=[];register({post:(p,h)=>routes.set(p,h)},async(strings,...values)=>{queries.push(strings.join('?'));return [{id:'test',restaurantId:12}];},{env:{BUSINESS_REVIEW_KEY:configured}});let status=200,result;const res={set(){},status(s){status=s;return this;},json(b){result=b;return this;}};await routes.get(path)({headers:{authorization:'Bearer '+key},body},res);return {status,result,queries};}
test('private queue is closed without configuration and rejects wrong keys',async()=>{assert.equal((await run('/api/business-review/queue',{},'wrong','')).status,503);const r=await run('/api/business-review/queue',{},'wrong','k'.repeat(32));assert.equal(r.status,403);assert.equal(r.queries.length,0);const ok=await run('/api/business-review/queue');assert.equal(ok.status,200);assert.doesNotMatch(ok.queries[0],/email|phone|checkoutTokenHash/);});
test('approval requires explicit independent checks and valid source',async()=>{const b={submissionId:'11111111-1111-4111-8111-111111111111',status:'approved',notes:'Checked owner authority and menu details',evidenceUrl:'https://google.com/maps/example',checked:true};assert.equal((await run('/api/business-review/decision',{...b,checked:false})).status,400);assert.equal((await run('/api/business-review/decision',{...b,evidenceUrl:'https://google.com.evil.test'})).status,400);const r=await run('/api/business-review/decision',b);assert.equal(r.status,200);assert.match(r.queries[0],/approve_business_submission/);});

test('website and social approval evidence still requires private authentication and independent checks',async()=>{
 const b={submissionId:'11111111-1111-4111-8111-111111111111',status:'approved',notes:'Independently checked exact branch, owner authority, price and diet.',checked:true};
 for(const evidenceUrl of ['https://example.com/','https://www.instagram.com/examplecafe/','https://www.facebook.com/examplecafe']){const request={...b,evidenceUrl};const missing=await run('/api/business-review/decision',{...request,checked:false});assert.equal(missing.status,400);assert.equal(missing.queries.length,0);const denied=await run('/api/business-review/decision',request,'wrong','k'.repeat(32));assert.equal(denied.status,403);assert.equal(denied.queries.length,0);const allowed=await run('/api/business-review/decision',request);assert.equal(allowed.status,200);assert.match(allowed.queries[0],/approve_business_submission/);}
});
