const test=require('node:test'),assert=require('node:assert/strict'),{init}=require('../owner-media');
function ui(fetch){
 const nodes={};for(const id of ['mediaUploadForm','mediaStatus','mediaDish','mediaClaim','mediaAccess','loadMediaDishes','ownerMetrics','mediaUploads','mediaPermission','mediaFile','mediaKind','mediaEvidence'])nodes[id]={value:'',textContent:'',children:[],checked:true,handlers:{},addEventListener(n,h){this.handlers[n]=h;},replaceChildren(){this.children=[];this.textContent='';this.value='';},append(e){this.children.push(e);if(this===nodes.mediaDish&&!this.value)this.value=e.value;}};
 const submit={disabled:false};nodes.mediaUploadForm.querySelector=()=>submit;nodes.mediaClaim.value='claim-a';nodes.mediaAccess.value='private-test-a';nodes.mediaKind.value='dish';nodes.mediaFile.files=[{type:'image/png',size:100}];nodes.mediaEvidence.value='This exact dish photo is authorised.';
 init({getElementById:id=>nodes[id],createElement:()=>({})},fetch);return nodes;
}
const result=()=>({ok:true,json:async()=>({success:true,dishes:[{id:'dish-a',name:'Dish A',isVeg:true}],metrics:[{name:'Dish A',event:'menu_click',total:2}],media:[{id:'media-a',kind:'dish',status:'approved'}]})});
test('changing claim access immediately clears prior dish, uploads, metrics and consent',async()=>{const n=ui(async()=>result());await n.loadMediaDishes.onclick();assert.equal(n.mediaDish.value,'dish-a');assert.equal(n.ownerMetrics.children.length,1);assert.equal(n.mediaUploads.children.length,2);n.mediaPermission.checked=true;n.mediaClaim.value='claim-b';n.mediaClaim.handlers.input();assert.equal(n.mediaDish.children.length,0);assert.equal(n.ownerMetrics.children.length,0);assert.equal(n.mediaUploads.children.length,0);assert.equal(n.mediaPermission.checked,false);});
test('a delayed old-claim response cannot repopulate the dashboard after access changes',async()=>{let resolve;const n=ui(()=>new Promise(r=>resolve=r));const pending=n.loadMediaDishes.onclick();n.mediaAccess.value='private-test-b';n.mediaAccess.handlers.input();resolve(result());await pending;assert.equal(n.mediaDish.children.length,0);assert.equal(n.ownerMetrics.children.length,0);assert.match(n.mediaStatus.textContent,/access changed/);assert.equal(n.loadMediaDishes.disabled,false);});
test('failed reload clears old details and photo uploads cannot reuse another claim dishes',async()=>{let calls=0;const n=ui(async()=>{calls++;return calls===1?result():{ok:false,json:async()=>({success:false,error:'Access rejected'})};});await n.loadMediaDishes.onclick();await n.loadMediaDishes.onclick();assert.equal(n.mediaDish.children.length,0);assert.match(n.mediaStatus.textContent,/Access rejected/);await n.mediaUploadForm.onsubmit({preventDefault(){}});assert.equal(calls,2);assert.match(n.mediaStatus.textContent,/Load and select/);});
