const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const routes=[['business-review','/api/business-review/contact','BusinessSubmission'],['business-stars','/api/business-claims/review-contact','BusinessClaim']];
const id='11111111-1111-4111-8111-111111111111',key='k'.repeat(64);
function harness(name,rows=[],env={BUSINESS_REVIEW_KEY:key}){const handlers={},queries=[];require('../lib/'+name)({post:(p,h)=>handlers[p]=h},async(strings,...values)=>{queries.push({sql:strings.join('?'),values});if(rows instanceof Error)throw rows;return rows;},{env});return {queries,async call(path,body={},authorization='Bearer '+key){const headers={},res={code:200,set(k,v){headers[k]=v;},status(n){this.code=n;return this;},json(data){this.data=data;this.headers=headers;return this;}};await handlers[path]({body,headers:{authorization}},res);return res;}};}
test('both private contact routes reject missing, wrong or unconfigured access before SQL',async()=>{
 for(const [name,path] of routes){for(const authorization of ['', 'Bearer wrong']){const h=harness(name);const r=await h.call(path,{id},authorization);assert.equal(r.code,403);assert.equal(h.queries.length,0);assert.equal(r.headers['Cache-Control'],'no-store');assert.equal(r.data.contact,undefined);}const h=harness(name,[],{});assert.equal((await h.call(path,{id})).code,503);assert.equal(h.queries.length,0);}
});
test('private contact routes bind one pending reference and serialize only contact fields',async()=>{
 for(const [name,path,table] of routes){const row={contactName:'Submitted Owner',email:'owner@example.com',phone:'9999999999',tokenHash:'DO_NOT_RETURN',checkoutTokenHash:'PRIVATE_TOKEN',reviewNotes:'PRIVATE_NOTES'};const h=harness(name,[row]);const r=await h.call(path,{id});assert.equal(r.code,200);assert.deepEqual(r.data.contact,{contactName:row.contactName,email:row.email,phone:row.phone});assert.equal(h.queries.length,1);const q=h.queries[0];assert.deepEqual(q.values,[id]);assert.ok(q.sql.includes('public."'+table+'"'));assert.match(q.sql,/status IN \('pending','needs_information'\)/);assert.doesNotMatch(q.sql,/SELECT \*|tokenHash|checkoutTokenHash|reviewNotes/);for(const s of ['DO_NOT_RETURN','PRIVATE_TOKEN','PRIVATE_NOTES'])assert.ok(!JSON.stringify(r.data).includes(s));}
});
test('invalid references, unavailable records and SQL failures reveal no contacts',async()=>{
 for(const [name,path] of routes){for(const invalid of [undefined,[],[id],true,'not-a-reference']){const h=harness(name);assert.equal((await h.call(path,{id:invalid})).code,400);assert.equal(h.queries.length,0);}const missing=await harness(name,[]).call(path,{id});assert.equal(missing.code,404);assert.equal(missing.data.contact,undefined);const failed=await harness(name,new Error('secret database detail')).call(path,{id});assert.equal(failed.code,503);assert.ok(!JSON.stringify(failed.data).includes('secret'));}
});
function element(){return {value:key,textContent:'',children:[],handlers:{},append(e){this.children.push(e);},replaceChildren(){this.children=[];},addEventListener(n,h){this.handlers[n]=h;}};}
test('private contact UI hides loaded details and ignores responses after reviewer key changes',async()=>{
 const nodes=Object.fromEntries(['key','status','queue','claimQueue','feedbackQueue','mediaQueue','load'].map(n=>[n,element()]));let release;const document={getElementById:n=>nodes[n],createElement:element};const context={document,AbortSignal,fetch:()=>new Promise(r=>{release=r;})};vm.createContext(context);const html=fs.readFileSync('admin-review.html','utf8'),script=html.match(/<script>([\s\S]*?)<\/script>/)[1];vm.runInContext(script,context);const card=element();context.contactDetails(card,'/api/business-review/contact',id);const [button,box]=card.children;const pending=button.onclick();nodes.key.handlers.input();release({ok:true,json:async()=>({contact:{contactName:'Stale contact'}})});await pending;assert.equal(box.children.length,0);assert.match(nodes.status.textContent,/key changed/);
 context.fetch=async()=>({ok:true,json:async()=>({contact:{contactName:'Owner',email:'owner@example.com',phone:'9999999999'}})});await button.onclick();assert.equal(box.children.length,4);assert.ok(box.children[0].textContent.includes('unverified'));await button.onclick();assert.equal(box.children.length,0);
});
