const crypto=require('node:crypto');const {profileUrl}=require('./business-listings');
const uuid=s=>typeof s==='string' && /^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(s);
function text(v,min,max){if(typeof v!=='string' || v.trim().length<min || v.length>max)throw new Error('Complete the required details within the field limits.');return v.trim();}
function star(b){const name=text(b.dishName,1,160),price=Number(b.dishPrice),slot=Number(b.slot || 1);if(!Number.isFinite(price)||price<=0||price>100000||!Number.isInteger(slot)||slot<1||slot>3)throw new Error('Enter a valid dish price and slot.');if(!['vegetarian','non-vegetarian'].includes(b.diet))throw new Error('Choose the dietary type.');const menuUrl=text(b.menuUrl,1,2000);try{const u=new URL(menuUrl);if(u.protocol!=='https:'||u.username||u.password)throw 0;}catch{throw new Error('Add an HTTPS menu source link.');}if(!['most_ordered','customer_favourite','signature'].includes(b.popularityBasis))throw new Error('Choose why this is a star dish.');const popularityEvidence=text(b.popularityEvidence,20,2000);if(b.consent!==true)throw new Error('Confirm your authority and the accuracy of these details.');return {name,price,slot,isVeg:b.diet==='vegetarian',menuUrl,popularityBasis:b.popularityBasis,popularityEvidence};}
module.exports=function(app,sql,{env=process.env}={}){
 async function owner(b){if(!uuid(b?.claimId)||!/^[a-f0-9]{64}$/.test(b?.accessCode || ''))return null;const r=await sql`SELECT * FROM public."BusinessClaim" WHERE id=${b.claimId}::uuid`;const c=r[0],h=crypto.createHash('sha256').update(b.accessCode).digest('hex');return c && /^[a-f0-9]{64}$/.test(c.tokenHash) && crypto.timingSafeEqual(Buffer.from(h,'hex'),Buffer.from(c.tokenHash,'hex'))?c:null;}
 const fail=(res,code,error)=>res.status(code).json({success:false,error});
 app.post('/api/business-claims',async(req,res)=>{
  res.set('Cache-Control','no-store');const b=req.body || {};let s,contactName,email,phone,profile,proof;
  try{s=star(b);if(s.slot!==1)throw new Error('Your first star dish must use slot 1.');contactName=text(b.contactName,1,100);email=text(b.email,3,254).toLowerCase();phone=text(b.phone,10,20);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!/^\+?[\d\s()-]{10,20}$/.test(phone))throw new Error('Enter a valid email and phone number.');profile=profileUrl(b.profileUrl);if(!profile)throw new Error('Add your HTTPS Google or Zomato profile link.');proof=text(b.ownershipEvidence,20,2000);if(!/^(osm:(node|way|relation)\/\d+|restaurant:\d+)$/.test(b.businessId || ''))throw new Error('Select a business from the directory.');}catch(e){return fail(res,400,e.message);}
  try{
   let rows,sourceKey=null;
   if(b.businessId.startsWith('osm:')){sourceKey=b.businessId;rows=await sql`SELECT name,city,address,"restaurantId" FROM public."HorecaCandidate" WHERE "sourceKey"=${sourceKey}`;}
   else rows=await sql`SELECT name,city,address,id AS "restaurantId" FROM public."Restaurant" WHERE id=${Number(b.businessId.split(':')[1])}`;
   const business=rows[0];if(!business)return fail(res,404,'Business not found.');
   let city,address;try{city=text(business.city || b.city,1,150);address=text(business.address || b.address,1,1000);}catch{return fail(res,400,'Add the missing city and full business address so they can be verified.');}
   const id=crypto.randomUUID(),revision=crypto.randomUUID(),accessCode=crypto.randomBytes(32).toString('hex'),hash=crypto.createHash('sha256').update(accessCode).digest('hex');
   const duplicate=await sql`SELECT id FROM public."BusinessClaim" WHERE ("sourceKey"=${sourceKey} OR ("restaurantId" IS NOT NULL AND "restaurantId"=${business.restaurantId || null})) AND (status='approved' OR (email=${email} AND status IN ('pending','needs_information')))`;
   if(duplicate.length)return fail(res,409,'This business is already claimed or your claim is awaiting review. Use your existing claim reference and access code.');
   await sql`WITH claim AS (INSERT INTO public."BusinessClaim"(id,"sourceKey","restaurantId","businessName",city,address,"contactName",email,phone,"profileUrl","ownershipEvidence","tokenHash") VALUES(${id}::uuid,${sourceKey},${business.restaurantId || null},${business.name},${city},${address},${contactName},${email},${phone},${profile},${proof},${hash}) RETURNING id) INSERT INTO public."StarDishRevision"(id,"claimId",slot,name,price,"isVeg","menuUrl","popularityBasis","popularityEvidence") SELECT ${revision}::uuid,id,1,${s.name},${s.price},${s.isVeg},${s.menuUrl},${s.popularityBasis},${s.popularityEvidence} FROM claim`;
   res.status(201).json({success:true,claimId:id,accessCode,message:'Ownership claim and first star dish submitted for separate reviews. Save your private access code.'});
  }catch{return fail(res,503,'Could not save the claim. Please try again later.');}
 });
 app.post('/api/business-claims/status',async(req,res)=>{
  res.set('Cache-Control','no-store');try{const c=await owner(req.body);if(!c)return fail(res,403,'Enter your claim reference and private access code.');const limits=c.restaurantId?await sql`SELECT public.restaurant_star_limit(${c.restaurantId}) AS capacity`:[];const revisions=await sql`SELECT id,slot,name,price,"isVeg","menuUrl","popularityBasis",status,"createdAt" FROM public."StarDishRevision" WHERE "claimId"=${c.id}::uuid ORDER BY "createdAt" DESC LIMIT 30`;res.json({success:true,status:c.status,businessName:c.businessName,restaurantId:c.restaurantId,capacity:limits[0]?.capacity || 1,revisions});}catch{return fail(res,503,'Claim status is temporarily unavailable.');}
 });
 app.post('/api/business-claims/star-dish',async(req,res)=>{
  res.set('Cache-Control','no-store');let s;try{s=star(req.body || {});}catch(e){return fail(res,400,e.message);}
  try{const c=await owner(req.body);if(!c)return fail(res,403,'Enter your claim reference and private access code.');if(c.status!=='approved')return fail(res,409,'Ownership must be approved before you edit or add dishes.');const limits=await sql`SELECT public.restaurant_star_limit(${c.restaurantId}) AS capacity`;if(s.slot>limits[0].capacity)return fail(res,409,'This dish slot exceeds your current plan. Free: 1; monthly: 3; annual: 2. Paid checkout is currently paused.');await sql`INSERT INTO public."StarDishRevision"(id,"claimId",slot,name,price,"isVeg","menuUrl","popularityBasis","popularityEvidence") VALUES(${crypto.randomUUID()}::uuid,${c.id}::uuid,${s.slot},${s.name},${s.price},${s.isVeg},${s.menuUrl},${s.popularityBasis},${s.popularityEvidence})`;res.status(201).json({success:true,message:'Dish submitted for review. Your current approved dish stays live until this revision is approved.'});}catch{return fail(res,409,'Could not save this revision. There may already be a pending review for this slot.');}
 });
 function reviewer(req,res){res.set('Cache-Control','no-store');const secret=env.BUSINESS_REVIEW_KEY,h=s=>crypto.createHash('sha256').update(s).digest();if(!secret || secret.length<32){fail(res,503,'Private review access has not been configured.');return false;}if(!crypto.timingSafeEqual(h(req.headers.authorization || ''),h('Bearer '+secret))){fail(res,403,'Private reviewer access required.');return false;}return true;}
 app.post('/api/business-claims/review-queue',async(req,res)=>{if(!reviewer(req,res))return;try{const claims=await sql`SELECT id,"businessName",city,address,"profileUrl","ownershipEvidence",status FROM public."BusinessClaim" WHERE status IN ('pending','needs_information') ORDER BY "createdAt" LIMIT 100`;const dishes=await sql`SELECT s.id,s.slot,s.name,s.price,s."isVeg",s."menuUrl",s."popularityBasis",s."popularityEvidence",c."businessName",c.city FROM public."StarDishRevision" s JOIN public."BusinessClaim" c ON c.id=s."claimId" WHERE s.status='pending' AND c.status='approved' ORDER BY s."createdAt" LIMIT 100`;res.json({success:true,claims,dishes});}catch{fail(res,503,'Review queue unavailable.');}});
 app.post('/api/business-claims/review',async(req,res)=>{
  if(!reviewer(req,res))return;const b=req.body || {};if(!uuid(b.id)||!['claim','dish'].includes(b.kind)||!['approved','rejected','needs_information'].includes(b.status)||typeof b.notes!=='string'||b.notes.trim().length<20||b.notes.length>2000)return fail(res,400,'Enter the review decision and at least 20 characters of notes.');if(b.status==='approved' && b.checked!==true)return fail(res,400,'Confirm independent ownership or menu checks.');try{if(b.status==='approved'){if(b.kind==='claim')await sql`SELECT public.approve_business_claim(${b.id}::uuid,${b.notes})`;else await sql`SELECT public.approve_star_revision(${b.id}::uuid,${b.notes},${b.popularityVerified===true})`;}else if(b.kind==='claim')await sql`UPDATE public."BusinessClaim" SET status=${b.status},"reviewNotes"=${b.notes},"reviewedAt"=NOW() WHERE id=${b.id}::uuid AND status IN ('pending','needs_information')`;else await sql`UPDATE public."StarDishRevision" SET status=${b.status},"reviewNotes"=${b.notes},"reviewedAt"=NOW() WHERE id=${b.id}::uuid AND status='pending'`;res.json({success:true,message:'Review decision saved.'});}catch{fail(res,409,'Could not approve. Check for existing ownership, plan limits or a previously reviewed revision in Neon.');}
 });
};
module.exports.validateStar=star;
