const reviewerKey=require('./reviewer-config');
const crypto=require('node:crypto');
const uuid=s=>/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(s || '');
module.exports=function registerBusinessMedia(app,sql,{rawParser,getMetrics,env=process.env}={}){
 let ready;
 function init(){if(!ready)ready=sql`CREATE TABLE IF NOT EXISTS public."BusinessMedia" (id uuid PRIMARY KEY,"claimId" uuid NOT NULL REFERENCES public."BusinessClaim"(id),"restaurantId" integer NOT NULL REFERENCES public."Restaurant"(id),"dishId" integer REFERENCES public."Dish"(id),kind text NOT NULL,mime text NOT NULL,content bytea NOT NULL,"ingredientEvidence" text NOT NULL,status text NOT NULL DEFAULT 'pending',"createdAt" timestamptz NOT NULL DEFAULT NOW(),"reviewedAt" timestamptz)`.catch(e=>{ready=null;throw e;});return ready;}
 const validSecret=(supplied,expected)=>typeof expected==='string' && /^[a-f0-9]{64}$/.test(expected) && crypto.timingSafeEqual(crypto.createHash('sha256').update(supplied).digest(),Buffer.from(expected,'hex'));
 function reviewer(req,res){const expected=reviewerKey(env),h=s=>crypto.createHash('sha256').update(s).digest();if(!expected || expected.length<32){res.status(503).json({success:false,error:'Private review access has not been configured.'});return false;}if(!crypto.timingSafeEqual(h(req.headers.authorization || ''),h('Bearer '+expected))){res.status(403).json({success:false,error:'Private reviewer access required.'});return false;}return true;}
 app.post('/api/business-media/upload',rawParser || ((_req,_res,next)=>next()),async(req,res)=>{
  res.set('Cache-Control','no-store');const claimId=req.headers['x-claim-id'],kind=req.headers['x-media-kind'],dishId=Number(req.headers['x-dish-id']),mime=String(req.headers['content-type'] || '').split(';')[0];
  let evidence;try{evidence=decodeURIComponent(req.headers['x-ingredient-evidence'] || '');}catch{return res.status(400).json({success:false,error:'Invalid media evidence.'});}
  const file=req.body;
  const jpeg=Buffer.isBuffer(file)&&file.length>3&&file[0]===255&&file[1]===216&&file[2]===255;
  const png=Buffer.isBuffer(file)&&file.length>8&&file.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]));
  if(!uuid(claimId) || !['dish','menu'].includes(kind) || req.headers['x-media-permission']!=='confirmed' || typeof evidence!=='string' || evidence.trim().length<20 || evidence.length>1000 || !file?.length || file.length>2*1024*1024 || !((mime==='image/jpeg'&&jpeg)||(mime==='image/png'&&png)) || (kind==='dish'&&(!Number.isSafeInteger(dishId)||dishId<1)))return res.status(400).json({success:false,error:'Upload a JPEG or PNG under 2 MB, confirm permission, and provide evidence identifying the exact dish or menu.'});
  try{
   const claims=await sql`SELECT id,"restaurantId","tokenHash",status FROM public."BusinessClaim" WHERE id=${claimId}::uuid`;
   const c=claims[0],code=String(req.headers.authorization || '').replace(/^Bearer /,'');
   if(!c || !/^[a-f0-9]{64}$/.test(code) || !validSecret(code,c.tokenHash))return res.status(403).json({success:false,error:'Enter the correct ownership-claim reference and private access code.'});
   if(c.status!=='approved' || !c.restaurantId)return res.status(409).json({success:false,error:'Ownership must be approved before uploading media.'});
   if(kind==='dish'){const dishes=await sql`SELECT id FROM public."Dish" WHERE id=${dishId} AND "restaurantId"=${c.restaurantId}`;if(!dishes.length)return res.status(403).json({success:false,error:'Select a dish belonging to your verified restaurant.'});}
   await init();const id=crypto.randomUUID();
   const saved=await sql`INSERT INTO public."BusinessMedia" (id,"claimId","restaurantId","dishId",kind,mime,content,"ingredientEvidence") SELECT ${id}::uuid,${c.id}::uuid,${c.restaurantId},${kind==='dish'?dishId:null},${kind},${mime},decode(${file.toString('hex')},'hex'),${evidence.trim()} WHERE (SELECT COUNT(*) FROM public."BusinessMedia" WHERE "restaurantId"=${c.restaurantId} AND status IN ('pending','approved'))<10 AND (SELECT COALESCE(SUM(octet_length(content)),0) FROM public."BusinessMedia" WHERE status IN ('pending','approved'))<67108864 RETURNING id`;
   if(!saved.length)return res.status(409).json({success:false,error:'The media storage limit has been reached. Contact SuggestDish to review your existing uploads.'});
   res.status(201).json({success:true,id,message:'Media uploaded for review. It will not appear on dish cards until its identity, dietary match and permission are checked.'});
  }catch{res.status(503).json({success:false,error:'Media could not be saved. Please try again later.'});}
 });
 app.post('/api/business-media/dishes',async(req,res)=>{res.set('Cache-Control','no-store');const b=req.body || {};if(!uuid(b.claimId)||!/^[a-f0-9]{64}$/.test(b.accessCode || ''))return res.status(403).json({success:false,error:'Enter your ownership-claim reference and private access code.'});try{const rows=await sql`SELECT id,"restaurantId","tokenHash",status FROM public."BusinessClaim" WHERE id=${b.claimId}::uuid`;const c=rows[0];if(!c || !validSecret(b.accessCode,c.tokenHash))return res.status(403).json({success:false,error:'Incorrect claim credentials.'});if(c.status!=='approved')return res.status(409).json({success:false,error:'Ownership must be approved first.'});const dishes=await sql`SELECT d.id,d.name,d."isVeg" FROM public."RestaurantStarDish" s JOIN public."Dish" d ON d.id=s."dishId" WHERE s."restaurantId"=${c.restaurantId} AND s.slot<=public.restaurant_star_limit(${c.restaurantId}) ORDER BY s.slot`;await init();const media=await sql`SELECT id,kind,status,"createdAt" FROM public."BusinessMedia" WHERE "claimId"=${c.id}::uuid ORDER BY "createdAt" DESC LIMIT 30`;let metrics=null;try{if(getMetrics)metrics=await getMetrics(c.restaurantId);}catch{}res.json({success:true,dishes,media,metrics});}catch{res.status(503).json({success:false,error:'Owner media information is unavailable.'});}});
 app.post('/api/business-media/queue',async(req,res)=>{res.set('Cache-Control','no-store');if(!reviewer(req,res))return;try{await init();const media=await sql`SELECT m.id,m.kind,m.mime,m."ingredientEvidence",m."createdAt",d.name AS "dishName",d."isVeg",r.name AS restaurant FROM public."BusinessMedia" m LEFT JOIN public."Dish" d ON d.id=m."dishId" JOIN public."Restaurant" r ON r.id=m."restaurantId" WHERE m.status='pending' ORDER BY m."createdAt" LIMIT 50`;res.json({success:true,media});}catch{res.status(503).json({success:false,error:'Media review queue unavailable.'});}});
 app.post('/api/business-media/review',async(req,res)=>{res.set('Cache-Control','no-store');if(!reviewer(req,res))return;const b=req.body || {};if(!uuid(b.id)||!['approved','rejected'].includes(b.status)||(b.status==='approved'&&b.checked!==true))return res.status(400).json({success:false,error:'Confirm the exact dish, dietary identity and media permission before approval.'});try{await init();const changed=await sql`UPDATE public."BusinessMedia" SET status=${b.status},"reviewedAt"=NOW() WHERE id=${b.id}::uuid AND status='pending' RETURNING id`;if(!changed.length)return res.status(409).json({success:false,error:'This media is already reviewed or unavailable.'});res.json({success:true,message:'Media review saved.'});}catch{res.status(503).json({success:false,error:'Could not save media review.'});}});
 app.get('/api/business-media/:id',async(req,res)=>{if(!uuid(req.params.id))return res.status(404).end();try{const rows=await sql`SELECT mime,content,status FROM public."BusinessMedia" WHERE id=${req.params.id}::uuid AND status IN ('pending','approved')`;const m=rows[0];if(!m)return res.status(404).end();if(m.status!=='approved'&&!reviewer(req,res))return;const bytes=Buffer.isBuffer(m.content)?m.content:typeof m.content==='string'?Buffer.from(m.content.startsWith(String.fromCharCode(92)+'x')?m.content.slice(2):m.content,'hex'):Buffer.from(m.content);res.set('Content-Type',m.mime);res.set('X-Content-Type-Options','nosniff');res.set('Content-Security-Policy',"default-src 'none'; sandbox");res.set('Cache-Control',m.status==='approved'?'public, max-age=3600':'no-store');res.send(bytes);}catch{res.status(404).end();}});
};
